network:
  ethernets:
    eth0:
      dhcp4: true
      match:
        macaddress: 96:00:02:b7:61:2f
      nameservers:
        addresses:
        - 8.8.8.8
        - 1.1.1.1
      set-name: eth0
  version: 2
